destroy_all_instances(obj_enemy_spawner);
destroy_all_instances(obj_hud);
destroy_all_instances(obj_missile);
destroy_all_instances(obj_enemy_pink_bullet);
destroy_all_instances(obj_alien_scout);
destroy_all_instances(obj_alien_fighter);
destroy_all_instances(obj_alien_destroyer);